version: '3.9'

services:
  crud-service:
    image: uni-learn/crud:prod
    build:
      context: .
      dockerfile: CRUD/Dockerfile
    ports:
      - "8080:80"
    networks:
      - uni-learn-net

networks:
  uni-learn-net:
    driver: bridge